import { useEffect, useState } from "react";
import { Archive, ChevronDown, Download, FileCheck2, FileSearch, FolderOpen, Globe2, Hash, Languages, LockKeyhole, ShieldCheck, UploadCloud } from "lucide-react";
import { indicatorText, text } from "./i18n";
import type { AnalysisResult, Locale, ReportFormat } from "./types";
function riskClass(level: AnalysisResult["risk"]["level"]) { return `risk risk-${level}`; }
export default function App() {
  const [locale,setLocale]=useState<Locale>("en"); const [results,setResults]=useState<AnalysisResult[]>([]); const [selectedId,setSelectedId]=useState<string|null>(null); const [busy,setBusy]=useState(false); const [dragging,setDragging]=useState(false); const [message,setMessage]=useState<string|null>(null); const t=text(locale); const selected=results.find((item)=>item.sha256===selectedId)??results[0]??null;
  useEffect(()=>{document.documentElement.lang=locale==="ar"?"ar":"en";document.documentElement.dir=locale==="ar"?"rtl":"ltr";},[locale]);
  async function analyze(paths:string[]){if(!paths.length)return;setBusy(true);setMessage(null);try{const next=await window.fileguard.analyze(paths);setResults((current)=>[...next,...current.filter((item)=>!next.some((incoming)=>incoming.sha256===item.sha256))]);setSelectedId(next[0]?.sha256??null);}catch{setMessage(t.errors.analyze);}finally{setBusy(false);}}
  async function pick(){await analyze(await window.fileguard.pickFiles());} function drop(event:React.DragEvent<HTMLDivElement>){event.preventDefault();setDragging(false);const paths=Array.from(event.dataTransfer.files).map((file)=>(file as File & {path?:string}).path).filter((value):value is string=>Boolean(value));void analyze(paths);} async function exportReport(format:ReportFormat){if(!selected)return;const response=await window.fileguard.saveReport(selected,format,locale);setMessage(response.saved?`${t.export}: ${response.path}`:null);}
  return <main className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark"><ShieldCheck size={22}/></span><span><strong>{t.appName}</strong><small>{t.tagline}</small></span></div><div className="top-actions"><span className="privacy-pill"><LockKeyhole size={14}/>{t.privacy}</span><button className="language" onClick={()=>setLocale(locale==="en"?"ar":"en")}><Languages size={16}/>{t.language}</button></div></header><section className="hero"><div><p className="eyebrow"><FileSearch size={15}/>{t.eyebrow}</p><h1>{locale==="ar"?"افهم الملف قبل أن تثق به.":"Understand a file before you trust it."}</h1><p className="hero-copy">{t.dropBody}</p></div><div className="hero-stat"><span>{results.length}</span><small>{locale==="ar"?"ملفاً محللاً":"files analyzed"}</small></div></section><section className="workspace"><aside className="queue-panel"><div className="panel-heading"><span>{t.recent}</span><button onClick={pick} title={t.browse}><FolderOpen size={18}/></button></div>{results.length===0?<div className="queue-empty"><FileCheck2 size={28}/><p>{t.empty}</p></div>:<div className="queue-list">{results.map((result)=><button key={result.sha256} className={`queue-item ${selected?.sha256===result.sha256?"active":""}`} onClick={()=>setSelectedId(result.sha256)}><FileCheck2 size={17}/><span><b>{result.fileName}</b><small>{result.actualType}</small></span><em className={riskClass(result.risk.level)}>{result.risk.score}</em></button>)}</div>}</aside><section className="content-panel"><div className={`drop-zone ${dragging?"is-dragging":""}`} onDragOver={(event)=>{event.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={drop}><span className="drop-icon"><UploadCloud size={25}/></span><div><h2>{busy?(locale==="ar"?"جارٍ تحليل الملف محلياً…":"Analyzing locally…"):t.dropTitle}</h2><p>{t.dropBody}</p></div><button className="primary" onClick={pick} disabled={busy}>{busy?"…":t.browse}</button></div>{message&&<div className="notice" role="status">{message}</div>}{!selected?<EmptyState title={t.select} body={t.selectBody}/>:<AnalysisView analysis={selected} locale={locale} onExport={exportReport} onReveal={()=>window.fileguard.showInFolder(selected.filePath)}/>}</section></section><section className="principles"><Principle icon={<LockKeyhole size={20}/>} title={t.noRemote} body={t.noRemoteText}/><Principle icon={<Globe2 size={20}/>} title={t.explainable} body={t.explainableText}/><Principle icon={<ShieldCheck size={20}/>} title={t.responsible} body={t.responsibleText}/></section></main>;
}
function EmptyState({title,body}:{title:string;body:string}){return <div className="empty-state"><span><FileSearch size={30}/></span><h2>{title}</h2><p>{body}</p></div>;} function Principle({icon,title,body}:{icon:React.ReactNode;title:string;body:string}){return <article><span>{icon}</span><h3>{title}</h3><p>{body}</p></article>;}
function AnalysisView({analysis,locale,onExport,onReveal}:{analysis:AnalysisResult;locale:Locale;onExport:(format:ReportFormat)=>void;onReveal:()=>void}){const t=text(locale);return <section className="analysis-view"><div className="result-header"><div><p className="eyebrow"><Hash size={14}/>{t.localEvidence}</p><h2>{analysis.fileName}</h2><p>{analysis.actualType} · {analysis.sizeDisplay}</p></div><div className="result-actions"><button className="secondary" onClick={onReveal}><FolderOpen size={16}/>{t.reveal}</button><div className="export-group"><button className="primary"><Download size={16}/>{t.export}<ChevronDown size={14}/></button><div className="export-menu">{(["markdown","json","html"] as ReportFormat[]).map((format)=><button key={format} onClick={()=>onExport(format)}>{t.formats[format]}</button>)}</div></div></div></div><div className="summary-grid"><article className="risk-card"><small>{t.score}</small><strong className={riskClass(analysis.risk.level)}>{analysis.risk.score}</strong><span>{t.risk[analysis.risk.level]}</span></article><article><small>{t.type}</small><strong>{analysis.actualType}</strong><span>.{analysis.extension??"—"}</span></article><article className="hash-card"><small>{t.hash}</small><code>{analysis.sha256}</code><span>✓ {locale==="ar"?"لم يُشغّل الملف":"File was not executed"}</span></article></div><section className="evidence-section"><div className="section-heading"><h3>{t.evidence}</h3><span>{analysis.indicators.length}</span></div>{analysis.indicators.length===0?<p className="no-evidence">{t.noEvidence}</p>:<div className="evidence-list">{analysis.indicators.map((indicator)=>{const localized=indicatorText(locale,indicator);return <article key={indicator.id}><span className={`severity severity-${indicator.severity}`}>{indicator.severity}</span><div><h4>{localized.title}</h4><p>{localized.description}</p><code>{localized.evidence}</code></div></article>;})}</div>}</section>{analysis.archive&&<section className="archive-section"><div className="section-heading"><h3><Archive size={18}/>{t.archive}</h3><span>{analysis.archive.entryCount}</span></div><div className="archive-meta"><span>{t.nestedExecutables}: <b>{analysis.archive.nestedExecutableCount}</b></span><span>{t.macroProject}: <b>{analysis.archive.macroPresent?t.yes:t.no}</b></span></div><ul>{analysis.archive.entries.slice(0,12).map((entry)=><li key={entry}>{entry}</li>)}</ul></section>}</section>;}
