import type { Locale } from "./types";
export const copy = {
  en: { appName:"FileGuard",tagline:"Safe local file triage",privacy:"Local only · No execution · No upload",eyebrow:"SAFE LOCAL FILE TRIAGE",localEvidence:"LOCAL EVIDENCE",analyze:"Analyze files",dropTitle:"Drop files here for local triage",dropBody:"Files are read statically on this device. FileGuard never executes them or submits them to the cloud.",browse:"Choose files",recent:"Analysis queue",empty:"No files analyzed yet",select:"Select an analysis",selectBody:"FileGuard is designed to inspect static file evidence, never to execute the selected content.",score:"Risk score",evidence:"Evidence",archive:"Archive inventory",nestedExecutables:"Nested executable entries",macroProject:"Macro project",yes:"Yes",no:"No",hash:"SHA-256",export:"Export report",reveal:"Show in folder",type:"Detected type",size:"Size",analyzed:"Analyzed",noEvidence:"No elevated static indicators found.",noRemote:"Offline-first privacy",noRemoteText:"FileGuard does not send files, hashes, contents, or filenames to external services.",explainable:"Explainable scoring",explainableText:"Every score is composed from visible static indicators; it is not a malware verdict.",responsible:"Defensive triage only",responsibleText:"Treat findings as review leads and follow your organization’s incident-response process.",formats:{markdown:"Markdown",json:"JSON",html:"HTML"},risk:{clean:"No elevated signal",low:"Low",medium:"Medium",high:"High",critical:"Critical"},errors:{analyze:"The selected file could not be analyzed.",save:"The report could not be saved."},language:"العربية" },
  ar: { appName:"FileGuard",tagline:"فرز آمن للملفات محلياً",privacy:"محلي فقط · دون تشغيل · دون رفع",eyebrow:"فرز ملفات آمن ومحلي",localEvidence:"الأدلة المحلية",analyze:"فحص الملفات",dropTitle:"اسحب الملفات هنا للفرز المحلي",dropBody:"تُقرأ الملفات بشكل ثابت على هذا الجهاز. لا يشغّلها FileGuard ولا يرسلها إلى السحابة.",browse:"اختيار الملفات",recent:"قائمة التحليل",empty:"لم تُحلّل أي ملفات بعد",select:"اختر تحليلاً",selectBody:"صُمم FileGuard لفحص الأدلة الثابتة في الملفات، وليس لتشغيل المحتوى المحدد.",score:"درجة الخطورة",evidence:"الأدلة",archive:"محتويات الأرشيف",nestedExecutables:"ملفات تنفيذية داخلية",macroProject:"مشروع ماكرو",yes:"نعم",no:"لا",hash:"بصمة SHA-256",export:"تصدير التقرير",reveal:"إظهار في المجلد",type:"النوع المكتشف",size:"الحجم",analyzed:"وقت التحليل",noEvidence:"لم تُكتشف مؤشرات ثابتة مرتفعة.",noRemote:"خصوصية محلية أولاً",noRemoteText:"لا يرسل FileGuard الملفات أو البصمات أو المحتوى أو أسماء الملفات إلى أي خدمة خارجية.",explainable:"درجة قابلة للتفسير",explainableText:"تأتي كل درجة من مؤشرات ثابتة ظاهرة؛ وهي ليست حكماً نهائياً بأن الملف برمجية خبيثة.",responsible:"للتحليل الدفاعي فقط",responsibleText:"اعتبر النتائج نقاط مراجعة واتبع إجراءات الاستجابة للحوادث في مؤسستك.",formats:{markdown:"Markdown",json:"JSON",html:"HTML"},risk:{clean:"لا توجد إشارة مرتفعة",low:"منخفضة",medium:"متوسطة",high:"مرتفعة",critical:"حرجة"},errors:{analyze:"تعذر تحليل الملف المحدد.",save:"تعذر حفظ التقرير."},language:"English" },
} as const;
export function text(locale: Locale) { return copy[locale]; }

const arabicIndicators: Record<string, { title: string; description: string; evidence: string }> = {
  "filename.double_extension": { title: "امتداد مزدوج مضلل", description: "يظهر في اسم الملف امتداد مستند قبل امتداد تنفيذي.", evidence: "اسم ملف يحتوي امتدادات متعددة" },
  "filename.direction_override": { title: "محرف تغيير اتجاه النص", description: "يحتوي اسم الملف على محرف Unicode يمكن أن يغيّر ترتيب النص بصرياً.", evidence: "محرف تحكم بالاتجاه" },
  "type.extension_mismatch": { title: "اختلاف بين النوع والامتداد", description: "لا تتطابق بصمة الملف المكتشفة عادة مع امتداد الاسم.", evidence: "بصمة ونوع اسم مختلفان" },
  "pdf.active_content": { title: "علامة محتوى PDF نشط", description: "تتضمن بيانات PDF علامة JavaScript أو إجراء تلقائياً؛ وهي إشارة ثابتة وليست دليلاً قطعياً.", evidence: "علامة إجراء في PDF" },
  "pdf.embedded_or_launch": { title: "علامة تشغيل أو محتوى مضمّن في PDF", description: "تشير بيانات PDF إلى تشغيل أو ملف مضمّن أو محتوى تفاعلي.", evidence: "علامة قدرة في PDF" },
  "script.base64_decode": { title: "فك محتوى مرمّز", description: "يتضمن النص البرمجي نمطاً لفك ترميز Base64.", evidence: "نمط فك Base64" },
  "script.execution_api": { title: "واجهة تنفيذ في نص برمجي", description: "يتضمن النص البرمجي واجهة أو أمراً موجهاً للتنفيذ.", evidence: "نمط واجهة تنفيذ" },
  "script.system_launcher": { title: "إشارة إلى مشغّل نظام", description: "يشير النص البرمجي إلى مشغّل أوامر من النظام.", evidence: "نمط مشغّل نظام" },
  "archive.executable_entry": { title: "محتوى تنفيذي داخل الأرشيف", description: "يحتوي فهرس الأرشيف على ملف تنفيذي أو نص برمجي واحد أو أكثر.", evidence: "مدخل تنفيذي في الأرشيف" },
  "office.macro_project": { title: "مشروع ماكرو لـOffice", description: "تتضمن بنية ZIP المتوافقة مع Office ملف vbaProject.bin.", evidence: "vbaProject.bin" },
  "archive.encrypted_entry": { title: "مدخل مشفّر في الأرشيف", description: "بعض الملفات داخل الأرشيف مشفّرة ولا يمكن فحصها دون كلمة مرور.", evidence: "مدخل مشفّر" },
  "archive.parse_failure": { title: "تعذر جرد الأرشيف كاملاً", description: "تعذر تحليل بيانات أرشيف متوافقة مع ZIP. لم يُستخرج الملف ولم يُشغّل.", evidence: "فشل تحليل البيانات الوصفية" },
  "pe.executable": { title: "ملف تنفيذي لنظام Windows", description: "يبدأ الملف ببصمة PE الخاصة بـWindows. هذا وحده ليس مؤشراً على البرمجيات الخبيثة.", evidence: "بصمة MZ" },
};

export function indicatorText(locale: Locale, indicator: { id: string; title: string; description: string; evidence: string }) {
  return locale === "ar" ? arabicIndicators[indicator.id] ?? indicator : indicator;
}
