const fs = require("node:fs");
const fsp = require("node:fs/promises");
const path = require("node:path");
const crypto = require("node:crypto");
const AdmZip = require("adm-zip");
const MAX_STATIC_READ = 1024 * 1024;
const EXECUTABLE_EXTENSIONS = new Set(["exe", "msi", "bat", "cmd", "com", "scr", "ps1", "vbs", "js", "jse", "jar", "hta", "lnk"]);
const DOCUMENT_EXTENSIONS = new Set(["pdf", "doc", "docx", "xls", "xlsx", "ppt", "pptx", "txt", "rtf"]);
const TYPE_EXTENSIONS = { "Windows PE executable": new Set(["exe", "dll", "sys", "scr", "cpl", "com"]), "PDF document": new Set(["pdf"]), "ZIP archive": new Set(["zip", "docx", "xlsx", "pptx", "jar", "apk", "odt", "ods", "odp"]), "PNG image": new Set(["png"]), "JPEG image": new Set(["jpg", "jpeg"]), "ELF executable": new Set(["elf", "bin", "so"]), "RAR archive": new Set(["rar"]), "7-Zip archive": new Set(["7z"]) };
function formatBytes(bytes) { if (bytes < 1024) return `${bytes} B`; const units = ["KB", "MB", "GB"]; let value = bytes / 1024; let index = 0; while (value >= 1024 && index < units.length - 1) { value /= 1024; index += 1; } return `${value.toFixed(value >= 10 ? 1 : 2)} ${units[index]}`; }
async function readHead(filePath, bytes = MAX_STATIC_READ) { const handle = await fsp.open(filePath, "r"); try { const buffer = Buffer.alloc(bytes); const { bytesRead } = await handle.read(buffer, 0, bytes, 0); return buffer.subarray(0, bytesRead); } finally { await handle.close(); } }
function sha256(filePath) { return new Promise((resolve, reject) => { const hash = crypto.createHash("sha256"); const stream = fs.createReadStream(filePath); stream.on("error", reject); stream.on("data", (chunk) => hash.update(chunk)); stream.on("end", () => resolve(hash.digest("hex"))); }); }
function detectType(buffer) { if (buffer.subarray(0, 2).toString("ascii") === "MZ") return "Windows PE executable"; if (buffer.subarray(0, 4).toString("ascii") === "%PDF") return "PDF document"; if (buffer.subarray(0, 4).equals(Buffer.from([0x50,0x4b,0x03,0x04])) || buffer.subarray(0, 4).equals(Buffer.from([0x50,0x4b,0x05,0x06]))) return "ZIP archive"; if (buffer.subarray(0,8).equals(Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]))) return "PNG image"; if (buffer.subarray(0,3).equals(Buffer.from([0xff,0xd8,0xff]))) return "JPEG image"; if (buffer.subarray(0,4).equals(Buffer.from([0x7f,0x45,0x4c,0x46]))) return "ELF executable"; if (buffer.subarray(0,7).toString("ascii") === "Rar!\x1a\x07") return "RAR archive"; if (buffer.subarray(0,6).equals(Buffer.from([0x37,0x7a,0xbc,0xaf,0x27,0x1c]))) return "7-Zip archive"; return "Unclassified binary or text"; }
function addIndicator(list, id, severity, weight, title, description, evidence) { if (!list.some((item) => item.id === id)) list.push({ id, severity, weight, title, description, evidence }); }
function inspectFileName(fileName, actualType, extension, indicators) { const parts = fileName.toLowerCase().split("."); if (parts.length >= 3 && DOCUMENT_EXTENSIONS.has(parts.at(-2)) && EXECUTABLE_EXTENSIONS.has(parts.at(-1))) addIndicator(indicators,"filename.double_extension","high",35,"Misleading double extension","The filename presents a document-like extension before an executable extension.",fileName); if (/\u202e|\u202d|\u202b/.test(fileName)) addIndicator(indicators,"filename.direction_override","high",30,"Bidirectional override character","The filename contains a Unicode direction-control character that can visually reorder text.",fileName); if (actualType !== "Unclassified binary or text" && TYPE_EXTENSIONS[actualType] && !TYPE_EXTENSIONS[actualType].has(extension)) addIndicator(indicators,"type.extension_mismatch","medium",25,"Type and extension differ","The detected file signature does not normally match the filename extension.",`${actualType} / .${extension || "none"}`); }
function inspectStaticText(buffer, extension, indicators) { const text = buffer.toString("utf8").replace(/\0/g, ""); if (extension === "pdf" || buffer.subarray(0,4).toString("ascii") === "%PDF") { if (/\/(JavaScript|JS)\b/i.test(text) || /\/(OpenAction|AA)\b/i.test(text)) addIndicator(indicators,"pdf.active_content","high",35,"Active PDF content marker","PDF metadata contains a JavaScript or automatic-action marker. This is a static signal, not proof of malicious behavior.","PDF action dictionary marker"); if (/\/(Launch|EmbeddedFile|RichMedia)\b/i.test(text)) addIndicator(indicators,"pdf.embedded_or_launch","high",30,"PDF launch or embedded-content marker","PDF metadata refers to launch, embedded file, or rich-media functionality.","PDF capability marker"); } const scriptLike = ["ps1","vbs","js","jse","bat","cmd","hta","sh","py"].includes(extension); if (scriptLike) { if (/frombase64string|base64\s*-d|convert\.frombase64string/i.test(text)) addIndicator(indicators,"script.base64_decode","medium",20,"Encoded-content decoding","The inspected script text includes a base64-decoding pattern.","base64 decode pattern"); if (/invoke-expression|\biex\b|wscript\.shell|createobject\s*\(\s*["']wscript\.shell/i.test(text)) addIndicator(indicators,"script.execution_api","high",30,"Script execution API","The inspected script text includes an execution-oriented API or command pattern.","execution API pattern"); if (/powershell(?:\.exe)?|cmd\.exe|rundll32|regsvr32/i.test(text)) addIndicator(indicators,"script.system_launcher","medium",20,"System launcher reference","The inspected script text references a system command launcher.","system launcher pattern"); } }
function inspectArchive(filePath, indicators) { const archive = { entryCount: 0, entries: [], encryptedEntryCount: 0, nestedExecutableCount: 0, macroPresent: false }; try { const zip = new AdmZip(filePath); const entries = zip.getEntries(); archive.entryCount = entries.length; archive.entries = entries.slice(0,80).map((entry)=>entry.entryName); for (const entry of entries) { const ext = path.extname(entry.entryName).slice(1).toLowerCase(); if (EXECUTABLE_EXTENSIONS.has(ext)) archive.nestedExecutableCount += 1; if (/vbaProject\.bin$/i.test(entry.entryName)) archive.macroPresent = true; if ((entry.header.flags || 0) & 1) archive.encryptedEntryCount += 1; } if (archive.nestedExecutableCount) addIndicator(indicators,"archive.executable_entry","high",30,"Executable content inside archive","The archive inventory includes one or more executable or script-like entries.",`${archive.nestedExecutableCount} entry or entries`); if (archive.macroPresent) addIndicator(indicators,"office.macro_project","medium",25,"Office macro project","The Office-compatible ZIP structure includes vbaProject.bin.","vbaProject.bin"); if (archive.encryptedEntryCount) addIndicator(indicators,"archive.encrypted_entry","low",10,"Encrypted archive entries","Some archive entries are encrypted and cannot be statically inspected without a password.",`${archive.encryptedEntryCount} entry or entries`); } catch { addIndicator(indicators,"archive.parse_failure","low",5,"Archive could not be fully inventoried","The ZIP-compatible archive metadata could not be parsed. The file was not extracted or executed.","metadata parse failure"); } return archive; }
function determineRisk(indicators) { const score = Math.min(100, indicators.reduce((total,item)=>total+item.weight,0)); if (score >= 80) return { score, level: "critical" }; if (score >= 55) return { score, level: "high" }; if (score >= 25) return { score, level: "medium" }; if (score > 0) return { score, level: "low" }; return { score, level: "clean" }; }
async function analyzeFile(filePath) { const stat = await fsp.stat(filePath); if (!stat.isFile()) throw new Error("Only regular files can be analyzed."); const fileName = path.basename(filePath); const extension = path.extname(fileName).slice(1).toLowerCase(); const [head,digest] = await Promise.all([readHead(filePath),sha256(filePath)]); const actualType = detectType(head); const indicators = []; inspectFileName(fileName,actualType,extension,indicators); inspectStaticText(head,extension,indicators); const archive = actualType === "ZIP archive" ? inspectArchive(filePath, indicators) : null; if (actualType === "Windows PE executable") addIndicator(indicators,"pe.executable","low",5,"Windows executable","The file begins with a Windows PE signature. Executable status alone is not a malicious indicator.","MZ signature"); return { schemaVersion:"1.0", analyzedAt:new Date().toISOString(), fileName, filePath, extension:extension||null, sizeBytes:stat.size, sizeDisplay:formatBytes(stat.size), sha256:digest, actualType, indicators, archive, risk:determineRisk(indicators), privacy:{executed:false,uploaded:false,cloudReputationChecked:false} }; }
module.exports = { analyzeFile, detectType, determineRisk, formatBytes };
